module libinit missing dependencies
* error while building can't locate the libinit properly..
ERROR: echo "module libinit missing dependencies: //:libinit_RMX1851" && false
module libinit missing dependencies: //:libinit_RMX1851